name: 'Build Documentation'
description: 'Build the Vite documentation site with all required assets'

runs:
  using: 'composite'
  steps:
    - name: Build documentation site
      shell: bash
      run: |
        # Change to docs directory and install dependencies
        cd docs
        npm install --no-frozen-lockfile

        # Build the Vite documentation site (includes copy-docs)
        npm run build
