nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"
npmAlwaysAuth: true
npmAuthToken: ${NPM_TOKEN}

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

npmScopes:
  "fjell":
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}
